### ISSUE TITLE
Import/export through clipboard does not work

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/nodered-app-node#23]
The application is not properly copied.

The access key should not be part of the copy.

**Comment by FokkeZB** [comment]
Why shouldn't it be part of the copy? Can we even influence what fields Node-RED should and should not copy?

**Comment by johanstokking** [comment]
Not sure if we can influence it, but it seems that there's a container for server or account data. E.g., if you copy your Twitter node, it doesn't copy the credentials. It would be great if we can do this as well.

The other issue is that there was a bad reference when pasting a copied node which also appeared in the debug and/or console log. I have not reproduced this myself but I will when time permits. If this is desired please co-assign the issue to me.

**Comment by FokkeZB** [comment]
I'll look at it.. once we have production up

**Comment by FokkeZB** [comment]
Hey @johanstokking could you unassign or reassign this issue? Thx!

**Comment by FokkeZB** [comment]
Interesting, how did I do that automatically via a comment?

**Comment by johanstokking** [comment]
Should be done
