### ISSUE TITLE
Can't load flow editor in Chrome if installed locally (mac)

### ISSUE THREAD

**Issue by gxvigo** [TheThingsNetwork/nodered-app-node#41]
Hi There, 

I have installed locally on my mac latest version of node-red with npm.
When I try to open the flow editor (localhost:1880) the top bar shows up for few seconds than the browser returns the error: 
Aw, Snap!
Something went wrong while displaying this web page.
Can't see any error in Terminal, can't see any error in Chrome debug or network as devtools disconnect.
If I open the same page in Firefox, it just works fine.
I tried to completely wipe out node-red and reinstall but nothing changed.

Really puzzled by the situation.

Cheers.

**Comment by johanstokking** [comment]
@gxvigo thanks for reporting. Not sure how this is caused. Also it doesn't seem related to the Node-RED node of The Things Network, is it?

**Comment by gxvigo** [comment]
yeah... I believe you are actually right, I assumed this is the main Node-red git repo (..with a particular name). My issue is related to standard node-red.

**Comment by johanstokking** [comment]
OK, I understand the confusion, no problem! I'll close this one.
