### ISSUE TITLE
Events not known

### ISSUE THREAD

**Issue by goofy2k** [TheThingsNetwork/nodered-app-node#46]
It is not clear which values are accepted by the event field. Although the documentation tells that a wildcard (#) can be used, the node does not accept this.

**Comment by johanstokking** [comment]
Can you elaborate on "does not accept this"?

**Comment by goofy2k** [comment]
Hi Johan, when I enter a # sign as the event, the node responds that this
is not a valid entry.

BUT, yesterday I updated the nodes to a current version. I noticed that the
names of the nodes have changed. Also I need to discover the new behavior.
So it is best to withdraw the issue.

Apparently, the node info on nodered.org, npm and Github was not valid for
my version of the nodes!
Thanks
Fred

Op di 10 jul. 2018 05:13 schreef Johan Stokking <notifications@github.com>:

**Comment by johanstokking** [comment]
OK thanks for the heads up and glad to hear it's working now! Indeed that was a major update.

**Comment by goofy2k** [comment]
Hi Johan, I have the nodes up and running. I see activation events coming in in the events node (with event set to #).

By careful reading, and following the events link in the Quickstart I also discovered somewhat more on possible settings for events.

Unfortunately the messages generated by the events node do not contain info on the type of event (am I correct?). I also use the method to communicate via MQTT. The advantage of that approach is that for every incoming message the information on the type of event is in the topic of the message. This helps to see whats going on in my application.

Fred

**Comment by johanstokking** [comment]
Isn't that information put in `msg` (not in `msg.payload`)?

**Comment by goofy2k** [comment]
No... unfortunately not. You can also see it in the example responses in
the Quickstart.

Especially if one wants to discover what's going on (like me 😊) it is
useful to learn to what replacement of the wildcard the system is actually
responding.

Fred

Op di 10 jul. 2018 12:42 schreef Johan Stokking <notifications@github.com>:

**Comment by johanstokking** [comment]
You are right, indeed. This should be added. I'm creating a new issue.
