### ISSUE TITLE
node-red-contrib-ttn NOT WORKING !

### ISSUE THREAD

**Issue by max-rh** [TheThingsNetwork/nodered-app-node#48]
Hi there,
I was using node-red ttn node to receive traffic from my ttn applications, it was working fine till it stopped working few days ago, although it still shows that the node is still connected, any thoughts ?

I can see my sensors traffic on the gateway from ttn console, but still no data received in node-red.
Thanks

**Comment by johanstokking** [comment]
Do you see Node-RED reporting any errors? Does a reconnect help by chance?

**Comment by max-rh** [comment]
Hi John,
No, there is no any warnings at node-red, actually i have tried to reconnect (redeploy) multiple times, (even tried another Node-red platform) it shows no warnings or alerts, it actually shows that the nodes are connected.

FYI, i have tried TTN nodes and mqtt nodes by adding the DevID and AppKey for authentication and the required topic as in TTN documentation, it shows that the MQTT node is connected but still no data.

Thanks for you help

**Comment by goofy2k** [comment]
Do you normally  have more than one gateway receiving your traffic? If you
only have one gateway nearby (as I have) it could well be that the gateway
is down.

Fred

Op do 2 aug. 2018 13:15 schreef max-rh <notifications@github.com>:

**Comment by johanstokking** [comment]
@max-rh you need the App ID and App Access Key for authentication; the device ID and AppKey are for LoRaWAN authentication to the network.

Do you see data flowing in the Console?

**Comment by max-rh** [comment]
yes @johanstokking , i can see my sesnors traffic flowing in the console,
Attached is  a snapshot from my Node-Red platform, as you can see all node show "Connected" status.
and this flow was already working, it just stopped suddenly as i mentioned before.

Thanks John for you advice.

![nodered](https://user-images.githubusercontent.com/25219094/43663877-ab6703e0-9773-11e8-9d0f-d50e9a14584b.PNG)

**Comment by johanstokking** [comment]
Can you share a screenshot of the node settings with obscuring the app access key please?
