### ISSUE TITLE
No ttn app

### ISSUE THREAD

**Issue by solick** [TheThingsNetwork/nodered-app-node#49]
Hi, i had a working flow up and running and reinstalled the modules again for some reason. Now the ttn app node is missing. I tried to reinstall the module serveral times, restarted node etc. but still the problem remains.

Any idea on this?

**Comment by johanstokking** [comment]
Do you see any error or warning output from Node-RED?

Otherwise it seems like a general custom nodes installation issue.

**Comment by solick** [comment]
Sorry for the late response. No errors at node-red log. Other node installations works fine. It is only ttn. I can see the ttn event etc. nodes but cannot select an existing or create a new ttn node

**Comment by johanstokking** [comment]
Can you share your environment and reproduction steps?

**Comment by solick** [comment]
@johanstokking 
1. setup node-red with docker
     node-red-dev:
       image: nodered/node-red-docker
       container_name: node-red-dev
       logging: 
          options:
            max-size: "10m"
            max-file: "5"
      ports:
         - 1900:1880
      volumes:
         - /{path-to-docker-data}/node-red-dev/data:/data
      user: "1000:1000"
      restart: always
2. run node-red
3. install ttn (via nom install within the external data directory
4. all nodes available except the ttn app node.

I was able to reproduce it several times

**Comment by johanstokking** [comment]
And what is the environment and version? Can can you print the output of Node-RED, i.e. `docker logs ...`?

**Comment by solick** [comment]
@johanstokking i tested it under macOS and ubuntu 18.04 same result.

**Comment by johanstokking** [comment]
@solick thanks, again it is very helpful if you provide _version_ and _logs_ as requested.

Anyway, I tried this with:

```
28 Mar 14:23:52 - [info] Node-RED version: v0.20.3
28 Mar 14:23:52 - [info] Node.js  version: v11.10.0
28 Mar 14:23:52 - [info] Darwin 18.2.0 x64 LE
```

Installation is successful.

If you mean that `ttn app` is not a node in the palette, then that's intended, as `app` is a configuration node. You only use `uplink`, `downlink` and `event` in your flows. When you configure an application, you create an `app` node, which you can see in the section **Configuration Nodes** (from menu).

**Comment by solick** [comment]
Hi and sorry for the delay. node red throws the error that the ttn app is not found. 
I use the MQTT broker now which works fine for me and stopped trying get the node-red plugin working.

However here are the requested information:

`3 May 13:17:11 - [info] Node-RED version: v0.19.5
3 May 13:17:11 - [info] Node.js  version: v6.14.4
3 May 13:17:11 - [info] Linux 4.15.0-47-generic x64 LE`

**Comment by nottheedge** [comment]
Hi,

This issue is somehow followed? I'm running node-red in docker and it's still throwing the same message. 

Regards
