### ISSUE TITLE
Node-red-contrib-ttn I have error 14 not connected

### ISSUE THREAD

**Issue by youssef8991** [TheThingsNetwork/nodered-app-node#55]
The node ttn up link works for few minutes then stops ,i get this error please help 
![image](https://user-images.githubusercontent.com/45587166/49429719-d5c94200-f76e-11e8-8a9d-b1ec9d62ad4d.png)

**Comment by johanstokking** [comment]
I agree that the error is not very clean, but this is simply a connection failure. Please check application settings.
